### ISSUE TITLE
Segfault related to Notification style = Native

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#106]
Hi!
I noticed reproducible segfault.
Two users, let user B has "Notification style = Native". 
- user A sends msg to user B
- user B rejects invitation from native ui window (not from  systray notification)
- user A again sends msg to user B
- segfault

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f3d20335b1e in QCoreApplication::postEvent(QObject*, QEvent*, int) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
[Current thread is 1 (Thread 0x7f3d1d178800 (LWP 1397360))]
(gdb) bt
#0  0x00007f3d20335b1e in QCoreApplication::postEvent(QObject*, QEvent*, int) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x000055b460e9a964 in ChatWindowTabWidget::PrivateChatTab::removePendingAcceptWidget (this=0x55b461a7a3e0) at chatwindowtabwidget.cpp:100
#2  ChatWindowTabWidget::openPrivateMessageTab (this=0x55b4616cec60, nickname=...) at chatwindowtabwidget.cpp:131
#3  0x000055b460e951de in MainChatWindow::onNewPrivateConversation (this=0x55b4616cc370, nickname=...) at mainchatwindow.cpp:407
#4  0x00007f3d2035e458 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x000055b460eb5b39 in Czateria::ChatSession::newPrivateConversation (this=this@entry=0x55b4616c4070, _t1=...) at moc_chatsession.cpp:307
#6  0x000055b460eab526 in Czateria::ChatSession::handlePrivateMessage (this=0x55b4616c4070, json=...) at chatsession.cpp:434
#7  0x000055b460eacd65 in Czateria::ChatSession::onTextMessageReceived (this=0x55b4616c4070, text=...) at chatsession.cpp:350
#8  0x00007f3d2035e458 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f3d2087afa9 in QWebSocket::textMessageReceived(QString const&) () from /usr/lib/x86_64-linux-gnu/libQt5WebSockets.so.5
#10 0x00007f3d2035e458 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f3d2087c609 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebSockets.so.5
#12 0x00007f3d2087949a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebSockets.so.5
#13 0x00007f3d20865323 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebSockets.so.5
#14 0x00007f3d2035ed5a in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007f3d20fdea66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007f3d20fe80f0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007f3d2033293a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007f3d203355b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007f3d2038af67 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007f3d1f2b8fbd in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007f3d1f2b9240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007f3d1f2b92e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007f3d2038a565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007f3d203314db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007f3d20339246 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x000055b460e7ab44 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:46
(gdb)
```

**Comment by Arek-Arek** [comment]
Probably this is issue #105 . This is strange bcause usually I don't use Notification style=Native. But I recoll that sometimes I see this kind of query window in ui (I mean question in new tab not in new modal window), randomly.
