### ISSUE TITLE
Segfault related to disrupted network connection

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#108]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe2ce4b6214 in QNetworkReply::error() const () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
[Current thread is 1 (Thread 0x7fe2caf3f800 (LWP 1647255))]
(gdb) bt
#0  0x00007fe2ce4b6214 in QNetworkReply::error() const () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#1  0x00005609d3098f99 in Czateria::RoomListModel::onDownloadFinished (this=0x5609d3a81b00) at roomlistmodel.cpp:117
#2  0x00007fe2ce125458 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007fe2ce50a72c in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#4  0x00007fe2ce5bb7ce in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#5  0x00007fe2ce125d5a in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fe2ceda5a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007fe2cedaf0f0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007fe2ce0f993a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fe2ce0fc5b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fe2ce151f67 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007fe2cd08017d in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007fe2cd080400 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007fe2cd0804a3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007fe2ce151565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007fe2ce0f84db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007fe2cefa9c6d in QDialog::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007fe2cefe2456 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00005609d307fde0 in (anonymous namespace)::networkErrorMessageBox (parent=0x7ffeb3b10cc0, ui=<optimized out>, title=...) at mainwindow.h:34
#19 0x00005609d30800b0 in MainWindow::<lambda(auto:3)>::operator()<QJsonParseError> (__closure=0x5609d3c72180, err=...) at mainwindow.h:34
#20 QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QJsonParseError>, void, MainWindow::MainWindow(QNetworkAccessManager*, AppSettings&, Czateria::ChatSessionListener*, QWidget*)::<lambda(auto:3)> >::call (arg=<optimized out>, f=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:146
#21 QtPrivate::Functor<MainWindow::MainWindow(QNetworkAccessManager*, AppSettings&, Czateria::ChatSessionListener*, QWidget*)::<lambda(auto:3)>, 1>::call<QtPrivate::List<QJsonParseError>, void> (
    arg=<optimized out>, f=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:256
#22 QtPrivate::QFunctorSlotObject<MainWindow::MainWindow(QNetworkAccessManager*, AppSettings&, Czateria::ChatSessionListener*, QWidget*)::<lambda(auto:3)>, 1, QtPrivate::List<QJsonParseError>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=<optimized out>, this_=0x5609d3c72170, r=<optimized out>, a=<optimized out>, ret=<optimized out>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:439
#23 0x00007fe2ce125458 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00005609d30aac86 in Czateria::RoomListModel::jsonError (this=this@entry=0x5609d3a81b00, _t1=...) at moc_roomlistmodel.cpp:195
#25 0x00005609d3099105 in Czateria::RoomListModel::onDownloadFinished (this=0x5609d3a81b00) at roomlistmodel.cpp:128
#26 0x00007fe2ce125458 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007fe2ce50a72c in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#28 0x00007fe2ce5bb7ce in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#29 0x00007fe2ce125d5a in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007fe2ceda5a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007fe2cedaf0f0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007fe2ce0f993a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007fe2ce0fc5b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007fe2ce151f67 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007fe2cd08017d in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007fe2cd080400 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007fe2cd0804a3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007fe2ce151565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x00007fe2ce0f84db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00007fe2ce100246 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00005609d3070b44 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:46
```

**Comment by xavery** [comment]
Thanks.

**Comment by Arek-Arek** [comment]
Good to see you are alive!:)
Thank you for fix.

**Comment by xavery** [comment]
Yes, I'm most definitely alive. I just don't have a lot of energy to dabble with my own projects these days - work is really taking its toll on me.
